blog/blog/blog/apps/user_app/urls.py
from django.urls import path
from . import views


app_name = 'user_app'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),  # 注册
    path('active/', views.active, name='active'),  # 激活账号
    path('login/', views.LoginView.as_view(), name='login'),  # 登录
    path('send_find_password_email/', views.SendFindPasswordEmail.as_view(), name='send_find_password_email'),  # 发送重置密码邮件
    path('find_password/', views.FindPassword.as_view(), name='find_password'),  # 找回密码
    path('logout/', views.user_logout, name='logout'),  # 退出登录
    path('change_password/', views.change_password, name='change_password'),  # 修改密码
]

blog/blog/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('django_admin666/', admin.site.urls, name='django_admin'),  # 嗯，谁都不认识的后台管理路径
    path('mdeditor/', include('mdeditor.urls')),  # 富文本
    path('movies/search/', include('haystack.urls')),  # 全文检索，地址为form表单的action
    path('captcha/', include('captcha.urls')),  # 图形验证码
    path('user/', include('user_app.urls', namespace='user_app')),  # 用户模块
    path('blog/', include('blog_app.urls', namespace='blog_app')),  # 博客模块
    path('movies/', include('movie_app.urls', namespace='movie_app')),  # 电影模块
    path('fun_time/', include('fun_time_app.urls', namespace='fun_time_app')),  # 开心一刻模块
    path('', include('web_manage_app.urls', namespace='web_manage_app')),  # 首页，网站前台管理
]


# 开发环境media配置，部署上线时同静态文件一起在nginx里面配置
if settings.DEBUG:
    # 静态文件 (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/blog/apps/user_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from db.base_models import BaseModel


class UserModel(AbstractUser, BaseModel):
    """扩展auth_user"""
    avatar = models.ImageField(upload_to='avatar/',  # 默认上传到media/avatar/
                               default='avatar/default.jpg',
                               verbose_name='用户头像'
                               )
    # 邮箱唯一，用来邮箱登录
    email = models.EmailField(blank=True, unique=True, max_length=254, verbose_name='邮箱地址')

    class Meta:
        db_table = 'user'
        verbose_name_plural = '用户信息'

blog/blog/blog/apps/user_app/forms.py
from django import forms
from django.core.cache import cache
from captcha.fields import CaptchaField  # 图形验证码
import re


# 注册验证
class RegisterForm(forms.Form):
    username = forms.CharField(max_length=30, required=True, error_messages={
        'max_length': '用户名不能超过30个字符',
        'required': '用户名不能为空'
    })

    password = forms.CharField(min_length=6, required=True, error_messages={
        'min_length': '密码最小长度6位',
        'required': '密码不能为空',
    })

    captcha = CaptchaField()  # 验证码字段

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if re.match(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", email) is None:
            raise ValueError('邮箱格式不正确')
        return email


# 登录验证
class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, required=True, error_messages={
        'max_length': '用户名不能超过30个字符',
        'required': '用户名不能为空'
    })

    password = forms.CharField(min_length=6, required=True, error_messages={
        'min_length': '密码最小长度6位',
        'required': '密码不能为空',
    })

    captcha = CaptchaField()  # 验证码字段


# 修改密码表单验证
class PasswordForm(forms.Form):
    old_password = forms.CharField(required=True, error_messages={
        'required': '请输入旧密码',
    })
    new_password = forms.CharField(min_length=6, required=True, error_messages={
        'min_length': '密码最小长度6位',
        'required': '新密码不能为空',
    })


class FindPasswordForm(forms.Form):
    """找回密码表单验证"""
    email = forms.EmailField(required=True, error_messages={'required': '邮箱不能为空'})
    verification_code = forms.CharField(required=True, error_messages={'required': '验证码不能为空'})
    captcha = CaptchaField()  # 图片验证码字段

    # 验证邮箱格式
    def clean_email(self):
        """验证邮箱格式"""
        email = self.cleaned_data.get('email')
        if re.match(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", email) is None:
            raise forms.ValidationError('邮箱格式不正确')
        return email

    def clean_verification_code(self):
        """验证邮箱验证码"""
        email = self.cleaned_data.get('email')
        verification_code = self.cleaned_data.get('verification_code')
        cache_verification_code = cache.get('find_password_' + email)
        if verification_code != cache_verification_code:
            raise forms.ValidationError('验证码错误')
        return verification_code


# 留言表单验证
class LeaveAMessageForm(forms.Form):
    content = forms.CharField(required=True, error_messages={
        'required': '还没输入，咩都某拒',
    })

    captcha = CaptchaField()  # 验证码字段

blog/blog/blog/apps/user_app/views.py
import re
import random
from django.shortcuts import render, redirect, reverse, HttpResponse
from django.views import View
from django.http import JsonResponse
from django.core.cache import cache  # 缓存
from django.core.mail import send_mail  # 发送邮件
from itsdangerous import TimedJSONWebSignatureSerializer  # 生成token
from itsdangerous import SignatureExpired  # token超时发生的异常
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required  # 路由保护
from django.conf import settings  # 从settings.py里导入
from apps.user_app.models import UserModel
from apps.user_app.forms import RegisterForm, LoginForm, PasswordForm, FindPasswordForm
from utils.send_mail import send_find_password_mail
# 验证码的东西
from captcha.models import CaptchaStore
from captcha.helpers import captcha_image_url


class RegisterView(View):
    """用户注册"""
    def get(self, request):
        # 验证码
        hashkey = CaptchaStore.generate_key()
        image_url = captcha_image_url(hashkey)

        # 已登录的用户不能访问注册页码跟登录页面
        if request.user.is_authenticated:
            return redirect(reverse('blog_app:index'))
        return render(request, 'user_app/register.html', locals())

    def post(self, request):
        # 验证码
        hashkey = CaptchaStore.generate_key()
        image_url = captcha_image_url(hashkey)

        # 获取数据
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')

        # 验证表单
        form = RegisterForm(request.POST)
        if form.is_valid():
            # 判断用户名是否已存在
            if len(UserModel.objects.filter(username=username)) > 0:
                username_error = '用户名已存在'
                return render(request, 'user_app/register.html', locals())
            # 判断邮箱是否已存在
            if len(UserModel.objects.filter(email=email)) > 0:
                email_error = '该邮箱已被注册'
                return render(request, 'user_app/register.html', locals())
            try:
                # 注册，create_user会把密码加密
                user = UserModel.objects.create_user(username=username, password=password, email=email)
                user.is_active = 0  # 未激活激的用户
                user.save()
            except:
                error = '注册出错，请联系管理员'
                return render(request, 'user_app/register.html', locals())

            # 发送激活邮件
            # 1、生成加密token
            serializer = TimedJSONWebSignatureSerializer(settings.SECRET_KEY, 86400)  # 有效期一天
            info = {'id': user.id}  # 要加密的字典
            token = serializer.dumps(info)  # 加密，生成token
            token = token.decode('utf-8')  # 生成的token默认是byte类型，需要解码

            # 2、邮件模板,域名或主机名
            html = """<h1>%s,欢迎注册</h1> 点击下面链接激活账号(24小时后过期)<br> 
                        <a href="%s/user/active/?token=%s">%s/user/active/?token=%s</a>""" \
                   % (username, settings.HOST_URL, token, settings.HOST_URL, token)
            # 2、发送邮件
            send_mail('BYC账号激活', '', settings.EMAIL_HOST_USER, [email], html_message=html)
            return redirect(reverse('user_app:login'))
        # 表单验证失败，返回错误信息
        return render(request, 'user_app/register.html', locals(), {'form': form})


def active(request):
    """激活账号"""
    uid = None

    # 查看token是否过期
    try:
        serializer = TimedJSONWebSignatureSerializer(settings.SECRET_KEY, 86400)
        token = request.GET.get('token')
        info = serializer.loads(token)  # 解密，加密的时候是字典，解密的时候还是字典
        uid = info.get('id')
    except SignatureExpired as e:  # token过期的错误SignatureExpired
        try:
            user = UserModel.objects.get(pk=uid)  # 删除账号，让用户重新注册
            user.delete()
        except:
            pass
        return HttpResponse('激活链接已过期，请重新注册')

    # 查看用户是否存在
    user = UserModel.objects.filter(pk=uid).first()  # 在数据库里查找用户，找不到则表示用户不存在
    if not user:
        return HttpResponse('<h1>用户不存在,前往<a href="' + settings.HOST_URL + '/user/register">注册</a></h1>')
    # 激活用户
    try:
        if user.is_active == 1:
            return render(request, 'user_app/active.html')
        user.is_active = 1
        user.save()
        return render(request, 'user_app/active.html')
    except:
        return HttpResponse('激活失败，请联系管理员: 1251779123@qq.com')


class LoginView(View):
    """用户登录"""
    def get(self, request):
        """渲染登录页面"""
        # 生成验证码
        hashkey = CaptchaStore.generate_key()
        image_url = captcha_image_url(hashkey)

        # 已登录的用户不能访问注册页码跟登录页面
        if request.user.is_authenticated:
            return redirect(reverse('web_manage_app:index'))
        return render(request, 'user_app/login.html', {'hashkey': hashkey, 'image_url': image_url})

    def post(self, request):
        """处理表单数据"""
        # 生成验证码
        hashkey = CaptchaStore.generate_key()
        image_url = captcha_image_url(hashkey)

        # 获取表单数据
        data = request.POST.dict()
        username = data.get('username', '')
        password = data.get('password', '')

        # 验证表单
        form = LoginForm(request.POST)
        if form.is_valid():
            # 用户验证，如果用户名和密码正确，返回user对象，否则返回None
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse('web_manage_app:index'))
            else:
                error = '用户名或密码错误'
                password = ''
                return render(request, 'user_app/login.html', locals())
        else:
            return render(request, 'user_app/login.html', locals(), {'form': form})


class SendFindPasswordEmail(View):
    """发送重置密码邮件"""
    def post(self, request):
        # 一个空字典，code=0表示未发送邮件，1为已发送，需要前端判断，然后发送按钮倒计时
        data = {}
        # 接收数据
        email = request.POST.get('email')
        # 验证邮箱
        if re.match(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", email) is None:
            data = {'code': 0, 'msg': '邮箱格式错误'}
            return JsonResponse(data=data)
        # 是否已经发送过验证码
        if cache.get('find_password_'+email):
            data = {'code': 0, 'msg': '此邮箱已发送过验证码，请五分钟后再重试'}
            return JsonResponse(data=data)
        # 验证用户
        user = UserModel.objects.filter(email=email, is_active=1).first()
        if not user:
            data = {'code': 0, 'msg': '邮箱未注册'}
            return JsonResponse(data=data)
        # 生成邮箱验证码
        code = ''
        choice_str = '1234567890'
        for i in range(6):
            code += random.choice(choice_str)
        # 验证码放入缓存，key为email，有效时间五分钟
        try:
            cache.set('find_password_'+email, code, 300)
        except:
            data = {'code': 0, 'msg': '验证码缓存出错'}
            return JsonResponse(data=data)
        # 发送邮件
        send_find_password_mail(email=email, code=code, username=user.username)
        data = {'code': 1, 'msg': '邮件发送成功'}
        return JsonResponse(data=data)


class FindPassword(View):
    """重置密码"""
    def get(self, request):
        """渲染表单"""
        default_password = settings.DEFAULT_PASSWORD
        # 生成验证码
        hashkey = CaptchaStore.generate_key()
        image_url = captcha_image_url(hashkey)
        # 已登录的用户不能访问注册页码跟登录页面
        if request.user.is_authenticated:
            return redirect(reverse('web_manage_app:index'))
        return render(request, 'user_app/find_password.html', locals())

    def post(self, request):
        """处理邮箱找回密码"""
        default_password = settings.DEFAULT_PASSWORD
        # 生成图片验证码
        hashkey = CaptchaStore.generate_key()
        image_url = captcha_image_url(hashkey)
        # 接收数据
        email = request.POST.get('email', '')
        verification_code = request.POST.get('verification_code', '')
        # 表单验证
        form = FindPasswordForm(request.POST)
        if form.is_valid():
            # 重置密码
            user = UserModel.objects.filter(email=email).first()
            if user:
                try:
                    user.set_password(default_password)
                    user.save()  # 保存
                    msg = '重置密码成功！'
                except:
                    error = '重置密码失败！'
            else:
                error = '用户不存在！'
        return render(request, 'user_app/find_password.html', locals())


# 路由保护
@login_required(login_url='user_app:login')
def change_password(request):
    """修改密码"""
    if request.method == 'POST':
        form = PasswordForm(request.POST)  # 表单验证
        if form.is_valid():
            username = request.user.username
            old_password = request.POST.get('old_password')
            new_password = request.POST.get('new_password')

            # 用户验证，如果当前登录的用户名和表单输入的旧密码密码正确，则返回user对象，否则返回None
            user = authenticate(request, username=username, password=old_password)
            if user:
                try:
                    user = UserModel.objects.get(pk=request.user.id)  # 获取得用户实例对象
                    user.set_password(new_password)  # 修改密码
                    user.save()  # 保存
                    return redirect(reverse('user_app:login'))
                except:
                    return render(request, 'user_app/change_password.html', {'error': '出错了'})
            else:
                return render(request, 'user_app/change_password.html', {'msg': '密码不正确'})
        else:
            return render(request, 'user_app/change_password.html', {'form': form})
    # GET请求
    return render(request, 'user_app/change_password.html')


@login_required(login_url='user_app:login')
def user_logout(request):
    """退出登录"""
    logout(request)
    return redirect(reverse('web_manage_app:index'))

blog/blog/blog/templates/user_app/active.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>激活</title>
</head>
<body>
<h1>用户已激活，前往<a href="{% url 'user_app:login' %}">登录</a></h1>
</body>
</html>

blog/blog/blog/templates/user_app/change_password.html
{% extends 'base.html' %}      {# 加载父模板 #}


{% block header %}  {# 头 #}
<title>修改密码</title>
{% endblock header %}


{% block nav %}                         {# 导航栏 #}
{% endblock nav %}

{% block search %}                       {# 搜索框 #}
{% endblock search %}

{% block content %}                     {# 内容:修改密码 #}
<div class="container">
        <div class="row">
            <div class="col-md-5">
                <form action="" method="post">
                    {% csrf_token %}
                    <h1 class="title">BYC修改密码</h1>
                  <div class="form-group">
                    <label>旧密码</label>
                     <input type="password" class="form-control" placeholder="旧密码" name="old_password">
                      <div class="red">{{ form.old_password.errors }}{{ msg }}</div>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">新密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="新密码" name="new_password">
                    <div class="red">{{ form.new_password.errors }}</div>
                  </div>
                  <button type="submit" class="btn btn-default">提交</button>
                    <h1 class="red">{{ error }}</h1>
                </form>
              </div>
        </div>
    </div>
{% endblock content %}

blog/blog/blog/templates/user_app/find_password.html
{% extends 'base.html' %}      {# 加载父模板 #}

{% block header %}                        {# 头 #}
<title>重置密码</title>
{% endblock header %}


{% block nav %}{% endblock nav %}        {# 导航栏 #}

{% block search %}                       {# 搜索框 #}
{% endblock search %}

{% block content %}                     {# 内容:登录表单 #}
<div class="container">
        <div class="row">
            <div class="col-sm-5">
                 <form action="" method="post">
                    {% csrf_token %}
                  <h1 class="title">重置密码</h1>
                  <div class="form-group">
                    <input type="email" name="email" id="input_email" class="form-control" value="{{ email }}" placeholder="邮箱">
                    <div class="red">{{ form.email.errors }}</div>
                  </div>
                  <div class="input-group">
                     <input type="text" name="verification_code" value="{{ verification_code }}" class="form-control" placeholder="邮箱验证码">
                     <span class="input-group-btn">
                         <button type="button" class="btn btn-info" id="send_email_btn">
                            <span>发送</span>
                         </button>
                     </span>
                  </div>
                  <div class="red">{{ form.verification_code.errors }}</div>
                <input placeholder="请输入验证码" name="captcha_1" type="text">
                <img alt="验证码" src="{{ image_url }}">
                <input name="captcha_0" value="{{ hashkey }}" type="hidden">
                <div class="red">{{ form.captcha.errors }}</div>
                <input type="submit" class="btn btn-primary" value="重置密码">
                     <span>重置后的密码是：<b class="h4">{{ default_password }}</b>，请尽快修改密码！</span>
                </form>
                <p class="h4 red">{{ error }}</p>
                {% if msg %}
                <p class="h3">{{ msg }}重置密码成功！<a href="{% url 'user_app:login' %}" style="color: #709de5;">登录</a></p>
                {% endif %}
              </div>
        </div>
    </div>
{% endblock content %}
{% block script %}
    $('#send_email_btn').click(function(){
         // 点击后禁用，发送邮件成功后倒计时
         $('#send_email_btn').attr("disabled",true);
        // 获取邮箱
        var email = $('#input_email').val();
        // 发送ajax请求
        $.post(
                "{% url 'user_app:send_find_password_email' %}",
                {"email": email, "csrfmiddlewaretoken": "{{ csrf_token }}"},
                function(data){
                    if(data['code']==0){
                        alert(data['msg']);
                        $('#send_email_btn').attr("disabled",false);
                    }else if(data['code']==1){
                        // 60秒倒计时
                        var num = 60;
                        $('#send_email_btn span').text(num);
                        var timer = setInterval(function(){
                             num--;
                            $('#send_email_btn span').text(num);
                            if (num<=1){
                                 // 清除定时器
                                clearInterval(timer);
                                $('#send_email_btn span').text('发送');
                                $('#send_email_btn').attr("disabled",false);
                            }
                        }, 1000);
                        alert(data['msg']);
                    }
                }
        );
    });
{% endblock script %}

blog/blog/blog/templates/user_app/login.html
{% extends 'base.html' %}      {# 加载父模板 #}

{% block header %}                        {# 头 #}
<title>登录</title>
{% endblock header %}


{% block nav %}{% endblock nav %}                        {# 导航栏 #}

{% block search %}                       {# 搜索框 #}
{% endblock search %}

{% block content %}                     {# 内容:登录表单 #}
<div class="container">
        <div class="row">
            <div class="col-sm-5">
                <form action="" method="post">
                    {% csrf_token %}
                    <h1 class="title">登录BYC</h1>
                  <div class="form-group">
                    <label>用户名</label>
                     <input type="text" class="form-control" value="{{ username }}" placeholder="用户名" name="username">
                      <div class="red">{{ form.username.errors }}</div>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" value="{{ password }}" id="exampleInputPassword1" placeholder="密码" name="password">
                      <div class="red">{{ form.password.errors }}</div>
                  </div>
                    <input placeholder="请输入验证码" name="captcha_1" type="text" >
                    <img alt="验证码" src="{{ image_url }}">
                    <input name="captcha_0" value="{{ hashkey }}" type="hidden">
                    <div class="red">{{ form.captcha.errors }}</div>
                  <button type="submit" class="btn btn-primary">登录</button>
                    &nbsp;&nbsp;<a href="{% url 'user_app:find_password' %}">
                        <span class="h5">忘记密码？</span>
                        </a>
                </form>
                <br>
                 <div>没有账号?&nbsp;&nbsp;
                     <a href="{% url 'user_app:register' %}">
                         <span class="h4">立即注册</span>
                     </a>
                 </div>
                <p class="h5 red">{{ error }}</p>
              </div>
        </div>
    </div>
{% endblock content %}

blog/blog/blog/templates/user_app/register.html
{% extends 'base.html' %}      {# 加载父模板 #}


{% block header %}  {# 头 #}
<title>注册</title>
{% endblock header %}

{% block nav %}{% endblock nav %}                         {# 导航栏 #}

{% block search %}                       {# 搜索框 #}
{% endblock search %}

{% block content %}                     {# 内容:登录表单 #}
<div class="container">
        <div class="row">
            <div class="col-md-5">
                <form action="" method="post">
                    {% csrf_token %}
                    <h1 class="title">欢迎注册</h1>
                  <div class="form-group">
                    <label>用户名</label>
                     <input type="text" class="form-control" value="{{ username }}" placeholder="用户名" name="username">
                      <div class="red">{{ form.username.errors }}{{ username_error }}</div>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" value="{{ password }}" id="exampleInputPassword1" placeholder="密码" name="password">
                    <div class="red">{{ form.password.errors }}</div>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">邮箱(新注册的账号要激活后才能登录)</label>
                    <input type="email" class="form-control" value="{{ email }}" id="exampleInputEmail1" placeholder="邮箱" name="email">
                    <div class="red">{{ form.email.errors }}{{ email_error }}</div>
                  </div>
                    <input placeholder="请输入验证码" name="captcha_1" type="text" >
                    <img alt="验证码" src="{{ image_url }}">
                    <input name="captcha_0" value="{{ hashkey }}" type="hidden">
                    <div class="red">{{ form.captcha.errors }}</div>
                  <button type="submit" class="btn btn-primary">注册</button>
                </form>
                <br>
                <div>已经有账号了?&nbsp;&nbsp;
                    <a href="{% url 'user_app:login' %}">
                        <span class="h4">立即登录</span>
                    </a>
                </div>
                <p class="h5 red">{{ error }}</p>
              </div>
        </div>
    </div>
{% endblock content %}