blog/blog/blog/apps/blog_app/urls.py
from django.urls import path
from apps.blog_app import views

app_name = 'blog_app'

urlpatterns = [
    path('', views.BlogView.as_view(), name='blog'),  # 博客列表页
    path('blog_detail/', views.BlogDetailView.as_view(), name='blog_detail'),  # 博客详情页
]

blog/blog/blog/apps/user_app/urls.py
from django.urls import path
from . import views


app_name = 'user_app'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),  # 注册
    path('active/', views.active, name='active'),  # 激活账号
    path('login/', views.LoginView.as_view(), name='login'),  # 登录
    path('send_find_password_email/', views.SendFindPasswordEmail.as_view(), name='send_find_password_email'),  # 发送重置密码邮件
    path('find_password/', views.FindPassword.as_view(), name='find_password'),  # 找回密码
    path('logout/', views.user_logout, name='logout'),  # 退出登录
    path('change_password/', views.change_password, name='change_password'),  # 修改密码
]

blog/blog/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('django_admin666/', admin.site.urls, name='django_admin'),  # 嗯，谁都不认识的后台管理路径
    path('mdeditor/', include('mdeditor.urls')),  # 富文本
    path('movies/search/', include('haystack.urls')),  # 全文检索，地址为form表单的action
    path('captcha/', include('captcha.urls')),  # 图形验证码
    path('user/', include('user_app.urls', namespace='user_app')),  # 用户模块
    path('blog/', include('blog_app.urls', namespace='blog_app')),  # 博客模块
    path('movies/', include('movie_app.urls', namespace='movie_app')),  # 电影模块
    path('fun_time/', include('fun_time_app.urls', namespace='fun_time_app')),  # 开心一刻模块
    path('', include('web_manage_app.urls', namespace='web_manage_app')),  # 首页，网站前台管理
]


# 开发环境media配置，部署上线时同静态文件一起在nginx里面配置
if settings.DEBUG:
    # 静态文件 (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/blog/apps/blog_app/models.py
from django.db import models
from mdeditor.fields import MDTextField
from db.base_models import BaseModel


class BlogTypeModel(BaseModel):
    """文章分类"""
    type = models.CharField(max_length=100, verbose_name='文章类型')  # 分类：MySQL，python...

    def __str__(self):
        return self.type

    class Meta:
        db_table = 'blog_type'
        verbose_name_plural = '文章类型'


class BlogModel(BaseModel):
    """博客文章模型"""
    title = models.CharField(max_length=254, verbose_name='文章标题')
    content = MDTextField(verbose_name='正文')  # 正文, 富文本格式，渲染前要转换成HTML格式
    browse = models.IntegerField(default=0, verbose_name='阅读量')
    favour = models.IntegerField(default=0, verbose_name='获赞数')
    comment = models.IntegerField(default=0, blank=True, verbose_name='评论数')

    # 逻辑外键
    user = models.ForeignKey('user_app.UserModel',
                             on_delete=models.DO_NOTHING,
                             db_constraint=False,
                             verbose_name='作者')
    blog_type = models.ForeignKey('BlogTypeModel',
                                  on_delete=models.DO_NOTHING,
                                  db_constraint=False,
                                  verbose_name='文章分类')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'blog'
        verbose_name_plural = '博客'


class BlogCommentModel(BaseModel):
    """文章评论"""
    content = models.CharField(max_length=600, verbose_name='评论内容')
    # 逻辑外键
    user = models.ForeignKey('user_app.UserModel',
                             on_delete=models.DO_NOTHING,
                             db_constraint=False,
                             verbose_name='评论所属用户')
    blog = models.ForeignKey('BlogModel',
                             on_delete=models.DO_NOTHING,
                             db_constraint=False,
                             verbose_name='评论的文章')

    class Meta:
        db_table = 'blog_comment'
        verbose_name_plural = '文章评论'


class BlogFavourModel(models.Model):
    """文章点赞"""
    blog = models.ForeignKey('BlogModel',
                             on_delete=models.DO_NOTHING,
                             db_constraint=False,
                             verbose_name='用户点赞的文章')
    user = models.ForeignKey('user_app.UserModel',
                             on_delete=models.DO_NOTHING,
                             db_constraint=False,
                             verbose_name='点赞的用户')

    class Meta:
        db_table = 'blog_favour'
        verbose_name_plural = '文章评论'

blog/blog/blog/apps/blog_app/forms.py
from django import forms
from captcha.fields import CaptchaField  # 图形验证码


# 留言表单验证
class BlogCommentForm(forms.Form):
    content = forms.CharField(required=True, error_messages={
        'required': '还未输入内容',
    })

blog/blog/blog/apps/blog_app/views.py
from django.shortcuts import render, reverse, redirect
from django.views import View
from django.core.paginator import Paginator  # 分页
from django.core.cache import cache  # 缓存
from django.db.models import F, Count
from django.db import transaction
from django.conf import settings
import markdown
from apps.blog_app.forms import BlogCommentForm  # 文章评论表单验证类
from apps.blog_app.models import *
from utils.check_page_number import check_page_number


class BlogView(View):
    """博客列表页"""
    def get(self, request):
        """查询所有文章，分页展示"""
        # 1、查询所有文章
        type_id = request.GET.get('type_id', '')
        try:
            type_id = int(type_id)  # 按类型查询文章
            blogs = BlogModel.objects.filter(is_delete=0, blog_type=type_id).order_by('-id')  # 按时间降序
        except:
            blogs = BlogModel.objects.filter(is_delete=0).order_by('-id')  # 按时间降

        # 2、产生分页器
        paginator = Paginator(blogs, settings.NUM_PAGES)  # 每页显示条目数
        p = request.GET.get('page', 1)  # 获取页码
        page = check_page_number(page=p, paginator=paginator)
        pager = paginator.get_page(page)  # 请求的页

        # 文章按类型分组
        blog_type = BlogModel.objects.values('blog_type', 'blog_type__type', 'blog_type__id').annotate(Count('blog_type'))

        # 3、返回
        return render(request, 'blog_app/blog.html', locals())


class BlogDetailView(View):
    """博客详情页"""
    def get(self, request):
        """显示文章详情，文章评论"""
        bid = request.GET.get('bid')  # 获取文章id
        error = request.GET.get('error')  # post请求后会重定向，并带上error参数
        if bid and bid.isdigit():
            # 1、根据id查询文章
            blog = BlogModel.objects.filter(id=bid).first()
            if blog:
                # 文章浏览量: +1
                key = request.META['REMOTE_ADDR'] + str(blog.id)  # 缓存键：用户ip + 文章id
                if not cache.get(key):
                    try:
                        blog.browse += 1
                        blog.save()
                        cache.set(key, 1, 300)  # 缓存过期时间5分钟
                    except:
                        pass
            # 文章内容转换为html字符串
            blog.content = markdown.markdown(blog.content,
                                             extensions=[
                                                 # 扩展参考官方：https://python-markdown.github.io/extensions/
                                                 'markdown.extensions.extra',
                                                 'markdown.extensions.codehilite',
                                                 'markdown.extensions.toc'])

            # 2、查询文章所属评论，然后分页
            comments = BlogCommentModel.objects.filter(is_delete=0, blog_id=bid).order_by('-id')  # 文章的全部评论
            if comments:
                pager = None
                paginator = Paginator(comments, settings.NUM_PAGES)
                p = request.GET.get('page', 1)
                page = check_page_number(page=p, paginator=paginator)
                pager = paginator.get_page(page)  # 请求的页
        return render(request, 'blog_app/blog_detail.html', locals())

    def post(self, request):
        """post请求，处理提交的评论"""
        bid = request.POST.get('bid')  # 获取文章id
        error = ''
        if request.user.is_authenticated:
            content = request.POST.get('content','').strip()  # 获取评论内容，去除两边空格
            if content:
                # 创建一条评论
                comment = BlogCommentModel(content=content,
                                           user_id=request.user.id,
                                           blog_id=bid)
                blog_item = BlogModel.objects.filter(id=bid).first()
                if blog_item:
                    try:
                        # 显示开启事务，需要两张表一起修改，保持数据完整
                        with transaction.atomic():
                            BlogModel.objects.filter(id=bid).update(comment=F('comment') + 1)  # 文章评论数 +1
                            comment.save()  # 保存评论
                    except:
                        error = '评论保存失败'
                else:
                    error = '找不到对应的文章'
            else:
                error = '请输入内容'
        else:
            error = '请先登录'
        return redirect(f'/blog/blog_detail/?bid={bid}&error={error}#comment_list')

blog/blog/blog/templates/blog_app/blog.html
{% extends 'base.html' %}      {# 加载父模板 #}
{% load filters %}  {# 加载自定义过滤器 #}

{% block header %}  {# 头 #}
<meta name="description" content="python,django,flask,爬虫">
<link rel="stylesheet" type="text/css" href="/static/css/index.css">
<style>
    .text-muted {
        color: #aca6a6;
    }

    /* 评论数图标 */
    .comment { color: #aca6a6; }
    .comment:hover { color: #337ab7; }
    a:hover{
        text-decoration:none;
    }

    .blog_type_list>li>a { color:#6f9fea; }
    .blog_type_list>li>a:hover { color: #337ab7; }
</style>
<title>博客</title>
{% endblock header %}

{% block search %}{% endblock search %}  {# 搜索框 #}

{% block content %}                                 {# 内容 #}
 <div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="row">
                <ul class="blog_type_list">
                    <li class="h4">文章分类</li>
                    <li class="h4"><a href="{% url 'blog_app:blog' %}">全部</a></li>
                    {% for item in blog_type %}  {# 文章类型列表 #}
                    <li class="h4">
                        <a href="{% url 'blog_app:blog' %}?type_id={{ item.blog_type__id }}">
                            {{ item.blog_type__type }}({{ item.blog_type__count }})
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        {# 一条博客一行 #}
        <div class="col-md-10">
        {% for blog in pager.object_list %}
            <div class="row">
                 <div class="col-md-1">
                     <img src="{{ blog.user.avatar.url }}" alt="头像" class="img-thumbnail user_avatar">
                     {% if blog.user.is_superuser %}
                        <div class="text-center h6">BYC站长</div>
                     {% else %}
                        <div title="{{ blog.user.username }}">{{ blog.user.username | str_cut:5 }}</div>
                     {% endif %}
                 </div>
                 <div class="col-md-10">
                    <a href="{% url 'blog_app:blog_detail' %}?bid={{ blog.id }}" target="_blank">
                        <h4>{{ blog.title }}</h4>
                    </a>
                    <p>{{ blog.content | str_cut }}</p>
                    <div class="text-muted">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true" id="browse">{{ blog.browse }}&nbsp;</span>
                        <a href="{% url 'blog_app:blog_detail' %}?bid={{ blog.id }}#comment_list">
                            <span class="glyphicon glyphicon-comment comment" aria-hidden="true">{{ blog.comment }}&nbsp;</span>
                        </a>
                        <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true">{{ blog.favour }}&nbsp;</span>
                        <span>发布于{{ blog.create_time | date:'Y年m月d日' }}</span>
                    </div>
                    <hr />
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
 </div>

<!--分页-->
<div class="text-center">
      <nav aria-label="Page navigation">
        <ul class="pagination">
           {% if pager.has_previous %}     {# 上一页 #}
            <li><a href="{% url 'blog_app:blog' %}?page=1&type_id={{ type_id }}">第1页</a></li>
          <li>
            <a href="{% url 'blog_app:blog' %}?page={{ pager.previous_page_number }}&type_id={{ type_id }}" aria-label="Previous">
              <span aria-hidden="true">上一页</span>
            </a>
          </li>
          {% endif %}
          <li><a href="javascript:;">{{ pager.number }}/{{ paginator.num_pages }}</a></li>
          {% if pager.has_next %}     {# 下一页 #}
          <li>
            <a href="{% url 'blog_app:blog' %}?page={{ pager.next_page_number }}&type_id={{ type_id }}" aria-label="Next">
              <span aria-hidden="true">下一页</span>
            </a>
          </li>
          {% endif %}
          {# 最后一页 #}
          <li><a href="{% url 'blog_app:blog' %}?page={{ paginator.num_pages }}&type_id={{ type_id }}">共{{ paginator.num_pages }}页</a></li>
        </ul>
      </nav>
</div>
{% endblock content %}

blog/blog/blog/templates/blog_app/blog_detail.html
{% extends 'base.html' %} {# 加载父模板 #}

{% block header %} {# 头 #}
<meta name="referrer" content="same-origin"> <!--同源带referrer头，不同源不带，针对csdn图片-->
<title>博客详情页</title>
<style>
	.content img { width:50%; }
</style>
{% endblock header %}

{% block search %}{% endblock search %} {# 不显示搜索框 #}
{% block nav %}
<ul class="nav navbar-nav navbar-right">
    {% if request.user.is_authenticated %}   {# 已登录的情况 #}
    <li class="li">
        <a href="javascript:void(0);">{{ request.user.username }} <span class="caret"></span></a>
        <ul class="ul_down nav navbar-nav">
            <li><a href="{% url 'user_app:logout' %}">退出登录</a></li>
            <li><a href="{% url 'user_app:change_password' %}">修改密码</a></li>

            {% if request.user.is_superuser %}   {# 登录用户是管理员 #}
            <li><a href="#">后台管理</a></li>
            <li><a href="/django_admin666/">django后台</a></li>
            {% endif %}
        </ul>
    </li>
    {% else %}
    {# 未登录的情况 #}
    <li><a href="{% url 'user_app:login' %}">登录</a></li>
    <li><a href="{% url 'user_app:register' %}">注册</a></li>
    {% endif %}
</ul>
{% endblock nav %}

{% block content %} {# 内容 #}
{% if blog %}
<div class="container">
	<!--文章详情开始-->
	<div class="row">
		<div class="col-md-10">
				<h1>{{ blog.title }}</h1>
				<div class="text-muted">
					<span class="glyphicon glyphicon-eye-open">{{ blog.browse }}&nbsp;</span>
					<span>最近更新 {{ blog.update_time | date:'Y年m月d日' }}</span>
				</div>
				<hr />
				<p class="content">{{ blog.content | safe }}</p>
		</div>
	</div>
	<!--文章详情结束-->

	<!--评论表单开始-->
	<br id="comment_list">  {# 评论跳转指定锚点 #}
	<hr>
	<br>
	<div class="row">
		<div class="col-md-8">
			<form action="" method="post">
				{% csrf_token %}
				<input name="bid" type="hidden" value="{{ blog.id }}">
				<input class="form-control" name="content" type="text" placeholder="评论">
				{% if error %}
				<div class="red">{{ error }}</div>
				{% endif %}
				<br>
				<input class="btn btn-success" type="submit" value="提交">
			</form>
		</div>
	</div>
	<!--评论表单结束-->
	{% if pager %}
	<br>
	<br>
	{% for comment in pager.object_list %}
	<div class="row">
		<div class="col-md-8">
			<div class="text-muted">
				<img src="{{ comment.user.avatar.url }}" class="user_avatar" alt="头像">
				<span>{{ comment.user.username }}</span>
			</div>
			<p class="lead">{{ comment.content }}</p>
			<p class="h6 text-muted">
				<span class="glyphicon glyphicon-time"></span>
				<i>{{ comment.create_time }}</i>
			</p>
		</div>
	</div>
	<hr>
	{% endfor %}
	{% endif %}  {# pager #}
	<!--评论结束-->
</div>

<!--分页-->
<div class="text-center">
      <nav aria-label="Page navigation">
        <ul class="pagination">
		{% if pager.has_previous %}     {# 上一页 #}
            <li><a href="{% url 'blog_app:blog_detail' %}?page=1&bid={{ blog.id }}#comment_list">第1页</a></li>
          <li>
            <a href="{% url 'blog_app:blog_detail' %}?page={{ pager.previous_page_number }}&bid={{ blog.id }}#comment_list" aria-label="Previous">
              <span aria-hidden="true">上一页</span>
            </a>
          </li>
	    {% endif %}
          <li><a href="javascript:;">{{ pager.number }}/{{ paginator.num_pages }}</a></li>
		{% if pager.has_next %}     {# 下一页 #}
          <li>
            <a href="{% url 'blog_app:blog_detail' %}?page={{ pager.next_page_number }}&bid={{ blog.id }}#comment_list" aria-label="Next">
              <span aria-hidden="true">下一页</span>
            </a>
          </li>
	    {% endif %}
          {# 最后一页 #}
          <li><a href="{% url 'blog_app:blog_detail' %}?page={{ paginator.num_pages }}&bid={{ blog.id }}#comment_list">共{{ paginator.num_pages }}页</a></li>
        </ul>
      </nav>
</div>
{% else %}
<div class="container">
	<div class="row">
		<div class="col-md-8">
			<p>无资源。。。。。。</p>
		</div>
	</div>
</div>
{% endif %}  {# blog #}
{% endblock content %}