blog/blog/blog/apps/blog_app/urls.py
from django.urls import path
from apps.blog_app import views

app_name = 'blog_app'

urlpatterns = [
    path('', views.BlogView.as_view(), name='blog'),  # 博客列表页
    path('blog_detail/', views.BlogDetailView.as_view(), name='blog_detail'),  # 博客详情页
]

blog/blog/blog/apps/fun_time_app/urls.py
from django.urls import path
from apps.fun_time_app import views

app_name = 'fun_time_app'

urlpatterns = [
    path('', views.DzView.as_view(), name='dz'),  # 段子
]

blog/blog/blog/apps/movie_app/urls.py
from django.urls import path
from apps.movie_app import views

app_name = 'movie_app'

urlpatterns = [
    path('', views.MovieView.as_view(), name='movies'),  # 电影首页
    path('<int:movie_id>/', views.MovieDetailView.as_view(), name='movie_detail'),  # 电影详情页
]

blog/blog/blog/apps/user_app/urls.py
from django.urls import path
from . import views


app_name = 'user_app'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),  # 注册
    path('active/', views.active, name='active'),  # 激活账号
    path('login/', views.LoginView.as_view(), name='login'),  # 登录
    path('send_find_password_email/', views.SendFindPasswordEmail.as_view(), name='send_find_password_email'),  # 发送重置密码邮件
    path('find_password/', views.FindPassword.as_view(), name='find_password'),  # 找回密码
    path('logout/', views.user_logout, name='logout'),  # 退出登录
    path('change_password/', views.change_password, name='change_password'),  # 修改密码
]

blog/blog/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('django_admin666/', admin.site.urls, name='django_admin'),  # 嗯，谁都不认识的后台管理路径
    path('mdeditor/', include('mdeditor.urls')),  # 富文本
    path('movies/search/', include('haystack.urls')),  # 全文检索，地址为form表单的action
    path('captcha/', include('captcha.urls')),  # 图形验证码
    path('user/', include('user_app.urls', namespace='user_app')),  # 用户模块
    path('blog/', include('blog_app.urls', namespace='blog_app')),  # 博客模块
    path('movies/', include('movie_app.urls', namespace='movie_app')),  # 电影模块
    path('fun_time/', include('fun_time_app.urls', namespace='fun_time_app')),  # 开心一刻模块
    path('', include('web_manage_app.urls', namespace='web_manage_app')),  # 首页，网站前台管理
]


# 开发环境media配置，部署上线时同静态文件一起在nginx里面配置
if settings.DEBUG:
    # 静态文件 (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/blog/templates/base.html
<!DOCTYPE html>
{% load static %}         {# 加载静态文件css、js#}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <link rel="shortcut icon" href="/static/images/favicon.ico" />
    <!--    <script src="/static/jquery/jquery-1.12.4.js"></script>-->
    <script src="https://labfile.oss.aliyuncs.com/courses/3774/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="/static/css/normalize.css">
    <link rel="stylesheet" href="/static/css/base.css">
    {% block header %}{% endblock header %}
</head>

<body>
    <!--菜单栏开始-->
    <nav class="navbar navbar-inverse">
        <!--切换按钮开始-->
        <button class="navbar-toggle" id="nav-btn">
            <span class="color-white glyphicon glyphicon-chevron-left" id="btn-span"></span>
        </button>
        <!--切换按钮结束-->

        <div class="container-fluid">
            <div class="navbar-header">
                <a href="{% url 'web_manage_app:index' %}" class="navbar-brand">
                    <img src="/static/images/logo.jpg" alt="logo">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="nav-div">
                 {% block nav %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'web_manage_app:index' %}">首页</a></li>
                    <li><a href="{% url 'blog_app:blog' %}">博客</a></li>
                    <li><a href="{% url 'movie_app:movies' %}">电影</a></li>
                    <li><a href="{% url 'fun_time_app:dz' %}">开心一刻</a></li>
                    <li><a href="{% url 'web_manage_app:leave_a_message' %}">留言板</a></li>
                    <li><a href="{% url 'web_manage_app:about' %}">关于我</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}   {# 已登录的情况 #}
                    <li class="li">
                        <a href="javascript:void(0);">{{ request.user.username }} <span class="caret"></span></a>
                        <ul class="ul_down nav navbar-nav">
                            <li><a href="{% url 'user_app:logout' %}">退出登录</a></li>
                            <li><a href="{% url 'user_app:change_password' %}">修改密码</a></li>

                            {% if request.user.is_superuser %}   {# 登录用户是管理员 #}
                            <li><a href="#">后台管理</a></li>
                            <li><a href="/django_admin666/">django后台</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    {% else %}
                    {# 未登录的情况 #}
                    <li><a href="{% url 'user_app:login' %}">登录</a></li>
                    <li><a href="{% url 'user_app:register' %}">注册</a></li>
                    {% endif %}
                </ul>
                {% endblock nav %}
            </div>
        </div>
    </nav>
    <!--头部结束-->

     <!--搜索框-->
    {% block search %}
     <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form class="navbar-form" method="post" action="">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" name="keyword" class="form-control" placeholder="搜索">
                    </div>
                    <button type="submit" class="btn btn-default" id="search_btn">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </form>
            </div>
        </div>
    </div>
 {% endblock search %}
    <!--身体开始-->
    {% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <p>内容</p>
            </div>
        </div>
    </div>
    {% endblock content %}
    <!--身体结束-->

     <!--底部开始-->
    <div class="bottom">
        <p class="h4">BYC个人网站</p>
        <p>
            <a href="https://beian.miit.gov.cn/#/Integrated/index" target='_blank'>桂ICP备2022008354号-1</a>
            &nbsp;&nbsp;联系邮箱：1251779123@qq.com
        </p>
    </div>
    <div id="bottom"></div>
    <!--底部结束-->

    <script>
        $('#nav-btn').click(function () {
            $('#nav-div').toggleClass('collapse');  // 点击出现下拉菜单

            if ($('#nav-div').hasClass('collapse')) {
                $('#btn-span').removeClass('glyphicon glyphicon-chevron-down').addClass('glyphicon glyphicon-chevron-left');
            }
            else {
                $('#btn-span').removeClass('glyphicon glyphicon-chevron-left').addClass('glyphicon glyphicon-chevron-down');
            }
            return false;  // 取消事件冒泡
        });

        // 当元素距离底部大于0时，添加固定定位css
        var b_height = $('#bottom').offset().top;
        var w_height = $(window).height();
        // 窗口可视区域高度 - 元素距离顶部高度 = 元素距离底部距离
        if (w_height - b_height > 0){
            $('.bottom').addClass('navbar-fixed-bottom');
        };
        if (w_height - b_height < 0){
            $('.bottom').removeClass('navbar-fixed-bottom');
        };
        {% block script %}
        {% endblock script %}
    </script>
</body>

</html>